package rules

import com.pany.adv.advtask.domain.Request
import com.pany.adv.advtask.domain.Archive
import com.pany.adv.advtask.service.ArchiveService
import java.util.Date

rule "Request Not Valid"

    dialect "java"

    when
        newRequest : Request(handler!=null, status=="Отклонено")
    then
        newRequest.setVersion(newRequest.getVersion()+1);
        newRequest.setDateProcessed(new Date());
     end

rule "Request Valid"

     dialect "java"

     when
         newRequest : Request(handler!=null, status=="Согласовано")
     then
         newRequest.setDateProcessed(new Date());
      end

